version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: pis_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: pis
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  backend:
    build: 
      context: ../../backend
    container_name: pis_backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgrespassword@db:5432/pis
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build: 
      context: ../../
      dockerfile: infra/docker/Dockerfile
    container_name: pis_frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
    restart: always

volumes:
  pgdata:
